import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compiledBodies } from '../../../scripts/lib/compiled-bodies.mjs';

const repo = fileURLToPath(new URL('../../../', import.meta.url));
const core = 'packages/core/src/runtime';
const worker = 'packages/worker/src';
const fabric = 'packages/fabric/src';
const outputs = [
  {
    path: `${core}/compiled-bodies.generated.ts`,
    taskImport: './facet-task.js',
    tasks: [
      ['CPYTHON_RUN_TASK', './cpython-runner.js', 'cpythonRunFacetFn'],
      ['WASM_CALL_TASK', './wasm-runner.js', 'wasmFacetCall'],
      ['CLANG_CALL_TASK', './clang-runner.js', 'clangFacetCall'],
      ['RUBY_CALL_TASK', './ruby-runner.js', 'rubyFacetCall'],
      ['BASH_STEP_TASK', './bash-runner.js', 'bashFacetStep'],
      ['BASH_REQUEST_TASK', './bash-runner.js', 'bashRequestStep'],
    ],
    bodies: [
      ['ESBUILD_FACET_RUNTIME_SOURCE', './esbuild-service.js', ['buildWithEsbuild']],
      ['TRANSFORM_FACET_RUNTIME_SOURCE', './esbuild-service.js', ['runTransformRequest']],
      ['OPENTUI_BACKEND_CLASS_SOURCE', './opentui-wasm-backend.js', ['OpenTUIWasmBackend']],
    ],
  },
  {
    path: `${fabric}/compiled-bodies.generated.ts`,
    tasks: [],
    bodies: [['INNER_DO_ADAPTER_SOURCE', './inner-do-env.js', ['innerDoAdapter', 'innerDoIdFromName']]],
  },
  {
    path: `${worker}/loaders/compiled-bodies.generated.ts`,
    taskImport: '@nimbus-sh/core/runtime/facet-task.js',
    tasks: [
      ['NPM_INSTALL_BATCH_TASK', '../npm/install-batch-facet.js', 'installPackagesInFacet'],
      ['NPM_RESOLVE_ONE_TASK', '../npm/resolve-one-facet.js', 'resolveOnePackumentInFacet'],
      ['PYTHON_REPL_TASK', '../runtime/python-repl.js', 'pythonReplStepRequestFn'],
      ['RUBY_REPL_TASK', '../runtime/ruby-repl.js', 'rubyReplStepFacetFn'],
      ['FANOUT_BENCH_TASK', './bench-tasks.js', 'fanoutBenchTask'],
      ['SERIAL_BENCH_TASK', './bench-tasks.js', 'serialBenchTask'],
    ],
    bodies: [
      ['NPM_INSTALL_HELPERS_SOURCE', null, [], [
        "export { retryDelayMs, retrying } from '@nimbus-sh/platform/retry.js';",
        "export { retryingRegistryFetch } from './packages/worker/src/npm/registry-retry.ts';",
        "export { sriDigestAlgorithms, sriEntries, strongestSriEntry, sriDigestOf, sriDigestsEqual } from '@nimbus-sh/core/_shared/tarball-integrity.js';",
      ].join('\n')],
      ['NPM_ABI_POLICY_SOURCE', '../facets/wasm-swap-registry.js', ['policyLookupSwap', 'policyLookupReject', 'policyNativePlatformReject', 'policyNativeBinAdvisory', 'policyLookupStagedArtifact', 'policyApplyStagedArtifact', 'policyIsOptionalNativeBinding']],
      ['RESIDENCY_MISS_REPORT_SOURCE', '../runtime/residency-miss-report.js', ['residencyMissReport']],
    ],
  },
];

/** Compile all bodies from one snapshot; self-generated imports cannot affect a body. */
export async function compileFacetBodies() {
  // Bootstrap missing generated modules for the first build; unused source
  // imports are tree-shaken. All real outputs are published together below.
  for (const output of outputs) {
    const names = [...output.tasks.map(([name]) => name), ...output.bodies.map(([name]) => name)];
    writeFileSync(resolve(repo, output.path), names.map((name) => `export const ${name} = undefined;`).join('\n'));
  }
  const written = [];
  for (const output of outputs) {
    const parent = dirname(resolve(repo, output.path));
    const lines = ['// Generated by scripts/compile-bodies.mjs; bundled expressions, never host function text.'];
    if (output.tasks.length) lines.push(`import { facetTaskSource } from ${JSON.stringify(output.taskImport)};`);
    for (const [name, entry, exported] of output.tasks) {
      const compiled = await compiledBodies({ entry: resolve(parent, entry.replace(/\.js$/, '.ts')), exports: [exported] });
      if (compiled.imports.length) throw new Error(`${name}: task expression has external imports: ${compiled.imports.join(' ')}`);
      const type = `typeof import(${JSON.stringify(entry)}).${exported}`;
      lines.push(`export const ${name} = facetTaskSource<Parameters<${type}>[0], Awaited<ReturnType<${type}>>>(${JSON.stringify(`${compiled.expression}.${exported}`)});`);
    }
    for (const [name, entry, names, contents] of output.bodies) {
      const compiled = await compiledBodies(contents ? { contents, resolveDir: repo } : { entry: resolve(parent, entry.replace(/\.js$/, '.ts')), exports: names });
      if (compiled.imports.length) throw new Error(`${name}: preamble has external imports: ${compiled.imports.join(' ')}`);
      lines.push(`export const ${name}: string = ${JSON.stringify(compiled.expression)};`);
    }
    written.push([resolve(repo, output.path), lines.join('\n') + '\n']);
  }
  for (const [path, source] of written) writeFileSync(path, source);
}
