/**
 * transform-pipeline.generated.ts — AUTO-GENERATED by
 * scripts/pin-transform-pipeline.mjs (core's build). DO NOT EDIT.
 *
 * The launch transform pipeline's code identity: the sha256 of the bundled
 * closure of runtime/bundle-cell-transform.ts and EsbuildService. The
 * worker's transform store keys every stored result by it, so no build
 * serves a result another build's pipeline produced.
 *
 * Closure: 504.53 KiB
 */

export const TRANSFORM_PIPELINE_ID: string = "9096fcedbccfed501e288e7053efbb14ca28eb73cc6a24c4a8c23281cc4df504";
