/**
 * transform-pipeline.generated.ts — AUTO-GENERATED by
 * scripts/pin-transform-pipeline.mjs (core's build). DO NOT EDIT.
 *
 * The launch transform pipeline's code identity: the sha256 of the bundled
 * closure of runtime/bundle-cell-transform.ts and EsbuildService. The
 * worker's transform store keys every stored result by it, so no build
 * serves a result another build's pipeline produced.
 *
 * Closure: 191.95 KiB
 */

export const TRANSFORM_PIPELINE_ID: string = "aeb22d0d131e7958c1304d795e633d5e9c3eb11928719519c4dbb9050be28e4b";
