/**
 * transform-pipeline.generated.ts — AUTO-GENERATED by
 * scripts/pin-transform-pipeline.mjs (core's build). DO NOT EDIT.
 *
 * The launch transform pipeline's code identity: the sha256 of the bundled
 * closure of runtime/bundle-cell-transform.ts and EsbuildService. The
 * worker's transform store keys every stored result by it, so no build
 * serves a result another build's pipeline produced.
 *
 * Closure: 187.77 KiB
 */

export const TRANSFORM_PIPELINE_ID: string = "4801b7cb2ef38b9c9dcde67a18d2f84a921f29a25ce301131c8ee11679e0fcd2";
