// AUTO-GENERATED by scripts/bundle-amaro-wasm.mjs. DO NOT EDIT.

export const AMARO_VERSION: string = "1.1.8";
export const AMARO_WASM_ASSET_PATH: string = "/_assets/amaro/amaro-2c8132e2c965a6a1.wasm";
export const AMARO_WASM_BUILD_ID: string = "2c8132e2c965a6a1";
export const AMARO_WASM_SHA256: string = "2c8132e2c965a6a10024bf83dcee287fe15a0cb90f987394d1f9f3d68053a851";
export const AMARO_WASM_BYTES: number = 2504689;
