/**
 * cirrus-plugin-react.generated.ts — AUTO-GENERATED by
 * scripts/bundle-plugin-react.mjs. DO NOT EDIT.
 *
 * Self-contained @vitejs/plugin-react@4.3.4 bundle with
 * @babel/core + react-refresh/babel + jsx-self/source plugins inlined.
 * Module-top fs.readFileSync calls for refreshUtils.js and
 * react-refresh-runtime.development.js are pre-resolved to string
 * constants at bundle time.
 *
 * Consumed by src/cirrus-real.ts at facet spawn — injected as a
 * LOADER module named 'cirrus-plugin-react.js'. User vite.config.ts'
 * `import react from '@vitejs/plugin-react'` is rewritten to point
 * at that module.
 *
 * [sdk-phase-1] The bundle string ships via the ASSETS binding instead
 * of inline. Use {@link getCirrusPluginReactBundle}. Version constant
 * stays inline.
 */

import { loadAssetText, type AssetsFetcher } from './runtime/assets-loader.js';

export const CIRRUS_PLUGIN_REACT_VERSION = "4.3.4";

/** Asset path for the bundle. Use {@link getCirrusPluginReactBundle}. */
export const CIRRUS_PLUGIN_REACT_BUNDLE_PATH = "/_assets/cirrus-plugin-react.bundle.js";

/**
 * Fetch the bundle string from the ASSETS binding. Cached per-isolate.
 *
 * @param env Object with the `ASSETS` binding.
 * @returns The plugin-react bundle as a UTF-8 string.
 * @throws {NimbusAssetLoadError} when binding missing or fetch fails.
 */
export function getCirrusPluginReactBundle(env: { ASSETS: AssetsFetcher }): Promise<string> {
  return loadAssetText(env.ASSETS, CIRRUS_PLUGIN_REACT_BUNDLE_PATH);
}
