/**
 * cirrus-npm-cjs.generated.ts — AUTO-GENERATED by
 * scripts/bundle-npm-cjs.mjs. DO NOT EDIT.
 *
 * Pre-bundled ESM artifacts for CJS packages in the React ecosystem
 * (react, react-dom, scheduler). Ships as a static Worker asset alongside
 * cirrus-plugin-react.
 * Consumed by src/cirrus-real.ts — injected as LOADER modules, and
 * the Vite resolver's output (e.g. /home/user/app/node_modules/react/index.js)
 * is rewritten to point at one of these bundles at request time.
 */

import { loadAssetText, type AssetsFetcher } from '@nimbus-sh/core/runtime/assets-loader.js';

export interface CirrusNpmCjsBundle {
  moduleName: string;
  code: string;
}

export const CIRRUS_NPM_CJS_VERSIONS: Record<string, string> = {
  "react": "18.3.1",
  "react-dom": "18.3.1",
  "scheduler": "0.23.2"
};

export const CIRRUS_NPM_CJS_BUNDLES_ASSET_PATH = "/_assets/cirrus-npm-cjs-bundles.json";

let __cirrusNpmCjsBundles: Promise<Record<string, CirrusNpmCjsBundle>> | null = null;

export function getCirrusNpmCjsBundles(env: { ASSETS: AssetsFetcher }): Promise<Record<string, CirrusNpmCjsBundle>> {
  if (!__cirrusNpmCjsBundles) {
    __cirrusNpmCjsBundles = loadAssetText(env.ASSETS, CIRRUS_NPM_CJS_BUNDLES_ASSET_PATH)
      .then((text) => JSON.parse(text) as Record<string, CirrusNpmCjsBundle>);
    __cirrusNpmCjsBundles.catch(() => {
      __cirrusNpmCjsBundles = null;
    });
  }
  return __cirrusNpmCjsBundles;
}
