/**
 * esbuild-cli-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runner of the `esbuild` command: esbuild-wasm/wasm_exec.js
 * (Go js/wasm glue, as __esbuildGoRuntime) followed by @nimbus-sh/core
 * src/runtime/esbuild-cli/preamble.ts as an IIFE. Only the session's esbuild
 * facet evaluates it, so src/runtime/esbuild-wasm-bytes.ts fetches it from
 * ASSETS when that facet is built, instead of the Worker bundle carrying it.
 * ESBUILD_CLI_BUILD_ID is a content-hash prefix, ESBUILD_CLI_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 36.34 KiB
 */

export const ESBUILD_CLI_ASSET_PATH: string = "/_assets/runtime/esbuild-cli-f427c21e610244ef.js";
export const ESBUILD_CLI_BUILD_ID: string = "f427c21e610244ef";
export const ESBUILD_CLI_SHA256: string = "f427c21e610244ef3b7ca92052f6eca290ea2b855f363815930f229e26885e49";
