/**
 * esbuild-cli-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runner of the `esbuild` command: esbuild-wasm/wasm_exec.js
 * (Go js/wasm glue, as __esbuildGoRuntime) followed by @nimbus-sh/core
 * src/runtime/esbuild-cli/preamble.ts as an IIFE. Only the session's esbuild
 * facet evaluates it, so src/runtime/esbuild-wasm-bytes.ts fetches it from
 * ASSETS when that facet is built, instead of the Worker bundle carrying it.
 * ESBUILD_CLI_BUILD_ID is a content-hash prefix, ESBUILD_CLI_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 235.01 KiB
 */

export const ESBUILD_CLI_ASSET_PATH: string = "/_assets/runtime/esbuild-cli-8b2ae6c4b08e41c6.js";
export const ESBUILD_CLI_BUILD_ID: string = "8b2ae6c4b08e41c6";
export const ESBUILD_CLI_SHA256: string = "8b2ae6c4b08e41c6cd945a59ea6a7d1917a26ee50545dff03bec055c6ca669a0";
