/**
 * esbuild-wasm-bundle.generated.ts — AUTO-GENERATED by scripts/bundle-esbuild-wasm.mjs
 * DO NOT EDIT.
 *
 * Digests of the staged esbuild-wasm 0.24.2 artifacts. Both live in
 * the static-assets layer, public/_assets/esbuild-0.24.2.{wasm,js},
 * and are fetched on demand and verified by src/runtime/esbuild-wasm-bytes.ts.
 *
 * The JS adapter is node_modules/esbuild-wasm/esm/browser.js with the
 * trailing `export { ... }` rewritten to `return { ... };`, so that
 * `new Function(body)()` yields the esbuild namespace inside a facet.
 * Why the browser build:
 *   - Pure ESM with no `createRequire`, no `require("fs")`, and
 *     no `process.binding` — safe to evaluate inside a workerd
 *     dynamic-worker isolate.
 *   - The supported public surface for "esbuild inside a worker" is
 *     exactly this build.
 *
 * Why `new Function(body)()` (rather than `import('data:...')`):
 *   - data: URL imports across workerd versions are not contractual
 *     and we don't want a deploy that worked yesterday to silently
 *     break tomorrow when the runtime is upgraded.
 *   - new Function is documented as supported inside dynamic workers
 *     (src/facet-manager.ts has been doing this since 2025).
 *
 * The bundle script verifies the file does NOT contain the forbidden
 * patterns (createRequire / dynamic node-builtin require / process.binding)
 * and bails loud if a future release reintroduces them.
 */
export const ESBUILD_WASM_VERSION: string = "0.24.2";
/**
 * Where the artifacts live inside env.ASSETS. Version-named, so a bump
 * lands under a new name and never serves a stale cache entry. Naming them
 * here is what puts them under scripts/dist-integrity.mjs's staged-asset
 * check, which discovers asset paths by value in generated modules.
 */
export const ESBUILD_WASM_ASSET_PATH: string = "/_assets/esbuild-0.24.2.wasm";
export const ESBUILD_JS_ASSET_PATH: string = "/_assets/esbuild-0.24.2.js";
/**
 * SHA-256 of the staged public/_assets/esbuild-0.24.2.wasm bytes.
 * src/runtime/esbuild-wasm-bytes.ts verifies every fetch against it — the L2
 * (caches.default) tier included — before the bytes reach workerd's loader.
 */
export const ESBUILD_WASM_SHA256: string = "e2b4b98297e04ef12981bafabf0a3c2d7c3c5cf6af603ef79d886deac3b5eeb3";
/** SHA-256 of the staged public/_assets/esbuild-0.24.2.js adapter, checked the same way. */
export const ESBUILD_JS_SHA256: string = "686b1cf18b0e47be54e74359a14daebb3cc2e2be1971ea57162242f60ca88266";
