/**
 * git-bundle.generated.ts — AUTO-GENERATED by scripts/bundle-git.mjs. DO NOT EDIT.
 *
 * Pins the staged copy of vendor/git.generated.mjs (isomorphic-git from
 * github:AshishKumar4/cf-git + isomorphic-git/http/web) that the git network
 * facet imports as `git-bundle.js`. GIT_BUNDLE_SHA256 is verified at fetch time.
 */

export const GIT_BUNDLE_ENTRY: string = "/_assets/runtime/git-de3e60c9f3ff006a.js";
export const GIT_BUNDLE_BUILD_ID: string = "de3e60c9f3ff006a";
export const GIT_BUNDLE_SHA256: string = "de3e60c9f3ff006a0befd7d8e2cbe29dc5628d033ae5081499d26cccd253732f";
