/**
 * git-bundle.generated.ts — AUTO-GENERATED by scripts/bundle-git.mjs. DO NOT EDIT.
 *
 * Pins the staged copy of vendor/git.generated.mjs (isomorphic-git from
 * github:AshishKumar4/cf-git + isomorphic-git/http/web) that the git network
 * facet imports as `git-bundle.js`. GIT_BUNDLE_SHA256 is verified at fetch time.
 */

export const GIT_BUNDLE_ENTRY: string = "/_assets/runtime/git-1eb4e822aae463fa.js";
export const GIT_BUNDLE_BUILD_ID: string = "1eb4e822aae463fa";
export const GIT_BUNDLE_SHA256: string = "1eb4e822aae463fa9994d14ec53d871180809b052d252efecfbff39116728359";
