/**
 * git-bundle.generated.ts — AUTO-GENERATED by scripts/bundle-git.mjs. DO NOT EDIT.
 *
 * Pins the staged copy of vendor/git.generated.mjs (isomorphic-git from
 * github:AshishKumar4/cf-git + isomorphic-git/http/web) that the git network
 * facet imports as `git-bundle.js`. GIT_BUNDLE_SHA256 is verified at fetch time.
 */

export const GIT_BUNDLE_ENTRY: string = "/_assets/runtime/git-ac02ccf1da220ae2.js";
export const GIT_BUNDLE_BUILD_ID: string = "ac02ccf1da220ae2";
export const GIT_BUNDLE_SHA256: string = "ac02ccf1da220ae260dfda1de837d54b2d717d92c0fbeff6ace1ba3e1b4ae162";
