/**
 * napi-wasm-artifacts.generated.ts — AUTO-GENERATED by scripts/bundle-napi-wasm.mjs
 * DO NOT EDIT.
 *
 * The threadless wasm32-wasip1 builds of napi-rs bindings
 * (scripts/napi-wasm/build.mjs, pins in scripts/napi-wasm/specs.mjs), staged
 * under public/_assets/napi-wasm/. runtime/staged-bindings.ts fetches each
 * file and verifies it against the digest below before it is compiled or
 * evaluated; PACKAGE_ABI_POLICY.stagedArtifacts routes each owner package and
 * the packages it requires the binding by to its entry.
 */

export interface NapiWasmAsset {
  readonly path: string;
  readonly sha256: string;
  readonly bytes: number;
}

export interface StagedBindingArtifact {
  /** The binding's name (scripts/napi-wasm/specs.mjs). */
  readonly name: string;
  /** The one version of `owner` the binding is built from. */
  readonly version: string;
  /** The package whose JavaScript loads the binding. */
  readonly owner: string;
  /** The package names that JavaScript requires the binding by. */
  readonly requiredAs: readonly string[];
  /** Wasm pages the binding's imported memory starts at (its declared minimum). */
  readonly memoryPages: number;
  readonly wasm: NapiWasmAsset;
}

export const NAPI_WASM_LOADER: NapiWasmAsset = {"path":"/_assets/napi-wasm/loader/200ad47a7f6f171e/napi-wasm-loader.mjs","sha256":"a122615f0f30d4d6305532848b32cd2cc3d0e3575476009da19278ac00dfed30","bytes":201937};
export const NAPI_WASM_TRAMPOLINE: NapiWasmAsset = {"path":"/_assets/napi-wasm/loader/200ad47a7f6f171e/wasi-trampoline.wasm","sha256":"0ad53da157e16656eee42877724d38aaa9876de20369f975f44b8a5e5d6f9cf6","bytes":1961};
export const STAGED_BINDING_ARTIFACTS: readonly StagedBindingArtifact[] = [
  {
    "name": "rolldown",
    "version": "1.2.11",
    "owner": "rolldown",
    "requiredAs": [
      "@rolldown/binding-wasm32-wasi"
    ],
    "memoryPages": 86,
    "wasm": {
      "path": "/_assets/napi-wasm/rolldown/1.2.11/rolldown.wasm",
      "sha256": "9e38287a3d6f106d50fa9eeb774f264130fd960a39f194d6380de731a4d7ed58",
      "bytes": 13472165
    }
  },
  {
    "name": "satteri",
    "version": "0.10.5",
    "owner": "satteri",
    "requiredAs": [
      "@bruits/satteri-wasm32-wasi"
    ],
    "memoryPages": 73,
    "wasm": {
      "path": "/_assets/napi-wasm/satteri/0.10.5/satteri.wasm",
      "sha256": "2c880e9ab1fb2a366dca6126e82cb5bdd3fba0b9308e74ce797c00f7d956f83e",
      "bytes": 3195967
    }
  },
  {
    "name": "astro-compiler",
    "version": "0.5.1",
    "owner": "@astrojs/compiler-binding",
    "requiredAs": [
      "@astrojs/compiler-binding-wasm32-wasi"
    ],
    "memoryPages": 68,
    "wasm": {
      "path": "/_assets/napi-wasm/astro-compiler/0.5.1/astro-compiler.wasm",
      "sha256": "9c68c5e8b97530c46f7b9d4998a26c3b7d68567755250a9118b0d14bcdcb680a",
      "bytes": 6585355
    }
  }
];
