/**
 * node-shims-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-node-shims.mjs. DO NOT EDIT.
 *
 * Pins the staged node-compat shim asset (the generateShimsCode() output
 * promoted out of the worker bundle). NODE_SHIMS_BUILD_ID is a content-hash
 * prefix so cache layers never serve stale bytes after a rebuild;
 * NODE_SHIMS_SHA256 is the full digest verified at fetch time.
 */

export const NODE_SHIMS_ENTRY: string = "/_assets/runtime/node-shims-0f0db68af3a424f5.js";
export const NODE_SHIMS_BUILD_ID: string = "0f0db68af3a424f5";
export const NODE_SHIMS_SHA256: string = "0f0db68af3a424f518df2a735a85a5153c66e349a57794053cc7a81029387614";
