/**
 * node-shims-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-node-shims.mjs. DO NOT EDIT.
 *
 * Pins the staged node-compat shim asset (the generateShimsCode() output
 * promoted out of the worker bundle). NODE_SHIMS_BUILD_ID is a content-hash
 * prefix so cache layers never serve stale bytes after a rebuild;
 * NODE_SHIMS_SHA256 is the full digest verified at fetch time.
 */

export const NODE_SHIMS_ENTRY: string = "/_assets/runtime/node-shims-3c59bb969d1b61a1.js";
export const NODE_SHIMS_BUILD_ID: string = "3c59bb969d1b61a1";
export const NODE_SHIMS_SHA256: string = "3c59bb969d1b61a1c08610fa885c14a6a1a02697cf7468425bcbaaab9ee6018e";
