/**
 * node-shims-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-node-shims.mjs. DO NOT EDIT.
 *
 * Pins the staged sources of the node-compat layer, promoted out of the worker
 * bundle: the shims, the VFS write ledger, the resident store, and the
 * runtime-code interpreter with its host module. Each
 * <NAME>_BUILD_ID is a content-hash prefix so cache layers never serve stale
 * bytes after a rebuild; <NAME>_SHA256 is the full digest verified at fetch time.
 */

/** dist/runtime/node-shims.js generateShimsCode() */
export const NODE_SHIMS_ENTRY: string = "/_assets/runtime/node-shims-920d3c142375cf83.js";
export const NODE_SHIMS_BUILD_ID: string = "920d3c142375cf83";
export const NODE_SHIMS_SHA256: string = "920d3c142375cf8349cbd6551863b1f9aef2ed8e4ef242f53e607c216da430d8";

/** @nimbus-sh/core dist/_shared/vfs-write-ledger.js VFS_WRITE_LEDGER_SOURCE */
export const VFS_WRITE_LEDGER_ENTRY: string = "/_assets/runtime/vfs-write-ledger-d33ee0034446c3e0.js";
export const VFS_WRITE_LEDGER_BUILD_ID: string = "d33ee0034446c3e0";
export const VFS_WRITE_LEDGER_SHA256: string = "d33ee0034446c3e087350fff3067664d97a95cdc73667d0f611a558d93fed533";

/** dist/vfs/facet-resident-store.js FACET_RESIDENT_STORE_SOURCE */
export const RESIDENT_STORE_ENTRY: string = "/_assets/runtime/resident-store-92386265e8b306dc.js";
export const RESIDENT_STORE_BUILD_ID: string = "92386265e8b306dc";
export const RESIDENT_STORE_SHA256: string = "92386265e8b306dcf276dc525ae9f7e025f4c0b7cad5b470ab674e836c8cb33c";

/** @nimbus-sh/core src/interpreter/primordials.ts, bundled by scripts/interpreter-bundle.mjs */
export const JS_INTERPRETER_PRIMORDIALS_ENTRY: string = "/_assets/runtime/js-interpreter-primordials-88814ac1a7910613.js";
export const JS_INTERPRETER_PRIMORDIALS_BUILD_ID: string = "88814ac1a7910613";
export const JS_INTERPRETER_PRIMORDIALS_SHA256: string = "88814ac1a79106130fca7b6731f02ee0952b8c2613a306da6b6de9653b4f570d";

/** @nimbus-sh/core src/interpreter, bundled by scripts/interpreter-bundle.mjs */
export const JS_INTERPRETER_ENTRY: string = "/_assets/runtime/js-interpreter-b20d9c61b65602d0.js";
export const JS_INTERPRETER_BUILD_ID: string = "b20d9c61b65602d0";
export const JS_INTERPRETER_SHA256: string = "b20d9c61b65602d0ce518c529b4cf2a1e2d48d3d0405e16d925ae13f2368a484";

/** @nimbus-sh/core src/interpreter/host-ops.ts HOST_OPS_SOURCE */
export const JS_INTERPRETER_OPS_ENTRY: string = "/_assets/runtime/js-interpreter-ops-2f4dfec6798e70fc.js";
export const JS_INTERPRETER_OPS_BUILD_ID: string = "2f4dfec6798e70fc";
export const JS_INTERPRETER_OPS_SHA256: string = "2f4dfec6798e70fcb11871ff1f57fa56336f33bfd5f31dfb3414f10433e4914c";
