/**
 * opencode-artifact.generated.ts — AUTO-GENERATED by scripts/bundle-opencode.mjs
 * DO NOT EDIT.
 *
 * Staged opencode-ai 1.16.2 JS bundle. The CLI bundle and its sidecar
 * assets (tree-sitter .wasm, highlight .scm) live in the static-assets layer
 * under public/_assets/opencode/1.16.2/ and are fetched on demand by
 * runtime/opencode-artifact.ts. PACKAGE_ABI_POLICY.stagedArtifacts maps
 * `opencode-ai` to this bundle.
 *
 * OPENCODE_ARTIFACT_PRESENT is false when the build host had no staged dist
 * directory (the upstream clone build output). The worker still builds; the
 * install policy surfaces a precise "artifact not staged" diagnostic instead
 * of selecting a missing bundle.
 *
 * OPENCODE_ARTIFACT_BUILD_ID is a content hash over the staged files. The
 * supervisor's L2 (caches.default) layer keys on it so a same-version rebuild
 * with different content never serves stale bytes from a warm colo cache.
 */

export const OPENCODE_ARTIFACT_VERSION: string = "1.16.2";
export const OPENCODE_ARTIFACT_BUILD_ID: string = "c9c58e7ec6b75d73";
export const OPENCODE_ARTIFACT_PRESENT: boolean = true;
export const OPENCODE_ARTIFACT_ENTRY: string = "/_assets/opencode/1.16.2/index.js";
export const OPENCODE_ARTIFACT_FILES: readonly string[] = ["bip-bop-01-ga21wr3r.mp3","bip-bop-03-kgfd4rq4.mp3","chunks.json","highlights-eq9cgrbb.scm","highlights-ghv9g403.scm","highlights-hk7bwhj4.scm","highlights-r812a2qc.scm","highlights-x6tmsnaa.scm","injections-73j83es3.scm","nope-03-2z8weyjw.mp3","parser.worker.js","photon_rs_bg-bq08arze.wasm","staplebops-06-rz29m246.mp3","tree-sitter-3jzf13jk.wasm","tree-sitter-bash-hq5s6fxb.wasm","tree-sitter-javascript-nd0q4pe9.wasm","tree-sitter-markdown-411r6y9b.wasm","tree-sitter-markdown_inline-j5349f42.wasm","tree-sitter-powershell-ryb2ffqs.wasm","tree-sitter-typescript-zxjzwt75.wasm","tree-sitter-zig-e78zbjpm.wasm","worker.js","yoga.wasm","yup-01-30ecpeh9.mp3"];

/**
 * Staged wasm sidecar filenames the facet runner pre-registers as
 * pre-compiled WebAssembly.Modules on `globalThis.__nimbusTreeSitterModules`
 * (request-time WebAssembly.compile is blocked in facets). Core + bash +
 * powershell cover opencode's bash tool. Null when the artifact is unstaged.
 */
export interface OpencodeTreeSitterWasms {
  readonly core: string;
  readonly bash: string;
  readonly powershell: string;
}
export const OPENCODE_TREE_SITTER_WASMS: OpencodeTreeSitterWasms | null = {"core":"tree-sitter-3jzf13jk.wasm","bash":"tree-sitter-bash-hq5s6fxb.wasm","powershell":"tree-sitter-powershell-ryb2ffqs.wasm"};

/**
 * Staged TUI worker bundle filenames. The opencode TUI client spawns its API
 * server (`server`) and OpenTUI its syntax-highlight parser (`parser`) via
 * `new Worker(...)`; the in-isolate Worker polyfill imports these from the
 * facet module map (FacetManager.opencodeWorkerModuleEntries). Null when the
 * artifact is unstaged or the workers were not built.
 */
export interface OpencodeTuiWorkers {
  readonly server: string;
  readonly parser: string;
}
export const OPENCODE_TUI_WORKERS: OpencodeTuiWorkers | null = {"server":"worker.js","parser":"parser.worker.js"};

/**
 * Staged yoga-layout wasm filename. OpenTUI lays out every TUI frame with
 * yoga; the runner pre-registers this as a pre-compiled WebAssembly.Module on
 * `globalThis.__nimbusYogaModule` (request-time WebAssembly.instantiate of
 * bytes is blocked in facets). Null when the artifact is unstaged.
 */
export const OPENCODE_YOGA_WASM: string | null = "yoga.wasm";

/**
 * Staged chunk-pack filename: one JSON asset mapping every split-build
 * `chunk-<hash>.js` module name to its ESM source. index.js and worker.js
 * share these chunks (code-splitting deduplicates the API-server code that,
 * bundled twice, pushed the TUI facet over the Worker memory limit); the
 * supervisor expands the pack into facet module-map entries per spawn. Null
 * when the artifact is unstaged.
 */
export const OPENCODE_CHUNKS_PACK: string | null = "chunks.json";
