/**
 * opentui-wasm-artifact.generated.ts — AUTO-GENERATED by
 * scripts/opentui/build-wasm.mjs. DO NOT EDIT.
 *
 * Staged OpenTUI 0.3.2 Zig core, built as a wasm32-wasi reactor
 * for the opencode TUI path. The artifact and its build manifest live in the
 * static-assets layer under public/_assets/opentui/0.3.2/.
 * See scripts/opentui/README.md for the build recipe and FFI ABI.
 *
 * Stage A: nothing consumes these constants yet; the facet module-map attach
 * path lands separately.
 *
 * OPENTUI_WASM_BUILD_ID is a content-hash prefix over the staged artifact so
 * cache layers keyed on it never serve stale bytes after a same-version
 * rebuild; OPENTUI_WASM_SHA256 is the full digest for integrity checks at
 * attach time.
 */

export const OPENTUI_WASM_VERSION: string = "0.3.2";
export const OPENTUI_WASM_BUILD_ID: string = "804a768bed34042e";
export const OPENTUI_WASM_ENTRY: string = "/_assets/opentui/0.3.2/opentui.wasm";
export const OPENTUI_WASM_SHA256: string = "804a768bed34042e0683787ad2780fdd037212182ed3bfc3b73a1c9b13336bed";
