/**
 * oxc-facet-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runtime of the transform facet: @nimbus-sh/core
 * src/runtime/oxc-facet/preamble.ts as an IIFE (the Oxc wasm's driver, the
 * dynamic-import rewrite and the top-level-await lowering). Only the
 * transform facet evaluates it, so src/runtime/oxc-wasm-bytes.ts fetches it
 * from ASSETS when that facet is built.
 * OXC_FACET_BUILD_ID is a content-hash prefix, OXC_FACET_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 332.60 KiB
 */

export const OXC_FACET_ASSET_PATH: string = "/_assets/runtime/oxc-facet-188b69b25dc96f75.js";
export const OXC_FACET_BUILD_ID: string = "188b69b25dc96f75";
export const OXC_FACET_SHA256: string = "188b69b25dc96f75af1ea825444f6c49bcf4f06d7deefcddf2bdcbaba06d32a8";
