/**
 * oxc-wasm-artifact.generated.ts — AUTO-GENERATED by scripts/bundle-oxc-wasm.mjs
 * DO NOT EDIT.
 *
 * Nimbus's Oxc transform (scripts/oxc-wasm, built by its build.mjs; inputs in
 * the staged provenance.json), staged under public/_assets/oxc/. The transform
 * facet's builder (runtime/oxc-wasm-bytes.ts) fetches it and verifies it
 * against OXC_WASM_SHA256 before the loader compiles it. The module imports
 * nothing; its memory starts at OXC_WASM_MEMORY_PAGES pages (stack and static
 * data) and grows only while a transform runs.
 *
 * oxc 0.152.0, rustc 1.98.1 (48a229cea 2026-09-01), 2.23 MiB
 */

export const OXC_VERSION: string = "0.152.0";
export const OXC_WASM_ASSET_PATH: string = "/_assets/oxc/nimbus-oxc-6cc596d8c5af28c7.wasm";
export const OXC_WASM_BUILD_ID: string = "6cc596d8c5af28c7";
export const OXC_WASM_SHA256: string = "6cc596d8c5af28c784505c21abd492e99af8b3bf0ac4b70b1f293ddd2641cd33";
export const OXC_WASM_BYTES: number = 2335230;
export const OXC_WASM_MEMORY_PAGES: number = 67;
