/**
 * oxc-facet-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runtime of the transform facet: @nimbus-sh/core
 * src/runtime/oxc-facet/preamble.ts as an IIFE (the Oxc wasm's driver, the
 * dynamic-import rewrite and the top-level-await lowering). Only the
 * transform facet evaluates it, so src/runtime/oxc-wasm-bytes.ts fetches it
 * from ASSETS when that facet is built.
 * OXC_FACET_BUILD_ID is a content-hash prefix, OXC_FACET_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 341.92 KiB
 */

export const OXC_FACET_ASSET_PATH: string = "/_assets/runtime/oxc-facet-ca07f8a6961468ab.js";
export const OXC_FACET_BUILD_ID: string = "ca07f8a6961468ab";
export const OXC_FACET_SHA256: string = "ca07f8a6961468ab25b341d43f4befe1970e204c702908394bd9e7d1264a2833";
