/**
 * oxc-facet-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runtime of the transform facet: @nimbus-sh/core
 * src/runtime/oxc-facet/preamble.ts as an IIFE (the Oxc wasm's driver, the
 * dynamic-import rewrite and the top-level-await lowering). Only the
 * transform facet evaluates it, so src/runtime/oxc-wasm-bytes.ts fetches it
 * from ASSETS when that facet is built.
 * OXC_FACET_BUILD_ID is a content-hash prefix, OXC_FACET_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 350.18 KiB
 */

export const OXC_FACET_ASSET_PATH: string = "/_assets/runtime/oxc-facet-76c545c96af77b88.js";
export const OXC_FACET_BUILD_ID: string = "76c545c96af77b88";
export const OXC_FACET_SHA256: string = "76c545c96af77b8858ab5acb6deb3820b05bb4970053dd66ee7a9c99875d6aa1";
