/**
 * rolldown-facet-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runtime of the build facet: scripts/rolldown-facet/entry.mjs
 * as an ES module (rolldown's JavaScript API over the staged threadless
 * binding, and @nimbus-sh/core runtime/rolldown-build.ts). Only the build
 * facet imports it, so facets/build-facet.ts fetches it from ASSETS when
 * that facet is built.
 * ROLLDOWN_FACET_BUILD_ID is a content-hash prefix, ROLLDOWN_FACET_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 600.27 KiB
 */

export const ROLLDOWN_FACET_ASSET_PATH: string = "/_assets/runtime/rolldown-facet-41cfa08e7faaa4f4.js";
export const ROLLDOWN_FACET_BUILD_ID: string = "41cfa08e7faaa4f4";
export const ROLLDOWN_FACET_SHA256: string = "41cfa08e7faaa4f4b51ff7c5910a87232d2c6417fb9c4a9a93e15f9bbd142bd6";
