/**
 * rolldown-facet-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runtime of the build facet: scripts/rolldown-facet/entry.mjs
 * as an ES module (rolldown's JavaScript API over the staged threadless
 * binding, and @nimbus-sh/core runtime/rolldown-build.ts). Only the build
 * facet imports it, so facets/build-facet.ts fetches it from ASSETS when
 * that facet is built.
 * ROLLDOWN_FACET_BUILD_ID is a content-hash prefix, ROLLDOWN_FACET_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 603.62 KiB
 */

export const ROLLDOWN_FACET_ASSET_PATH: string = "/_assets/runtime/rolldown-facet-271b492498e6ccf8.js";
export const ROLLDOWN_FACET_BUILD_ID: string = "271b492498e6ccf8";
export const ROLLDOWN_FACET_SHA256: string = "271b492498e6ccf86b21bcd32ede36f09af1fe648c0b8b3a6ecee65d0bd44dda";
