/**
 * rolldown-facet-artifact.generated.ts — AUTO-GENERATED by
 * scripts/bundle-facet-workers.mjs. DO NOT EDIT.
 *
 * Pins the staged runtime of the build facet: scripts/rolldown-facet/entry.mjs
 * as an ES module (rolldown's JavaScript API over the staged threadless
 * binding, and @nimbus-sh/core runtime/rolldown-build.ts). Only the build
 * facet imports it, so facets/build-facet.ts fetches it from ASSETS when
 * that facet is built.
 * ROLLDOWN_FACET_BUILD_ID is a content-hash prefix, ROLLDOWN_FACET_SHA256 the
 * digest every fetch is verified against.
 *
 * Size: 322.76 KiB
 */

export const ROLLDOWN_FACET_ASSET_PATH: string = "/_assets/runtime/rolldown-facet-63aff654691bdca0.js";
export const ROLLDOWN_FACET_BUILD_ID: string = "63aff654691bdca0";
export const ROLLDOWN_FACET_SHA256: string = "63aff654691bdca0c2a2346854b2de745cbb10f43c7e90b6c03b7877690954b3";
