// WASI Wave-2 fixtures — hand-rolled wasm snapshot_preview1 programs that
// exercise the file-IO codepaths (path_*, fd_filestat_*, fd_pread/pwrite,
// fd_readdir, path_rename overwriting-existing).
//
// Each fixture imports wasi_snapshot_preview1.<fns> + exports memory + _start.
// Bytes built by /tmp/build-wasi-w2-fixtures.mjs (see commit P1 evidence) and
// each fixture's exact behaviour is documented inline at the call site.
//
// Demo path conventions:
//   - The wasm-runner WASI mode passes argv[0] = the filename of the .wasm.
//   - preopens: fd=3 maps the user's session root (home/user/wasi-w2 here).
//
// 'cat' fixture takes argv[1] as the file path to read; hardcoded
// length 9 in the bytecode (matches 'hello.txt' — the demo path).

export const FIXTURES = {
  'path-write-read': 'AGFzbQEAAAABJgVgCX9/f39/fn5/fwF/YAR/f39/AX9gBH9/f38Bf2ABfwF/YAAAAokBBBZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxCXBhdGhfb3BlbgAAFndhc2lfc25hcHNob3RfcHJldmlldzEIZmRfd3JpdGUAARZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxB2ZkX3JlYWQAAhZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxCGZkX2Nsb3NlAAMDAgEEBQMBAAEHEwIGbWVtb3J5AgAGX3N0YXJ0AAQKtAEBsQEBAn9BA0EAQeQAQQlBAUL/////A0L/////A0EAQcAAEAAaQcAAKAIAIQBBIEHIATYCAEEkQQ42AgAgAEEgQQFBKBABGiAAEAMaQQNBAEHkAEEJQQBC/////wNC/////wNBAEHAABAAGkHAACgCACEAQSBBrAI2AgBBJEEWNgIAIABBIEEBQTAQAhpBMCgCACEBIAAQAxpBIEGsAjYCAEEkIAE2AgBBAUEgQQFBKBABGgsLJAIAQeQACwloZWxsby50eHQAQcgBCw53cml0ZStyZWFkIE9LCg==',
  'mkdir-readdir':   'AGFzbQEAAAABKQVgA39/fwF/YAl/f39/f35+f38Bf2AFf39/fn8Bf2AEf39/fwF/YAAAApkBBBZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxFXBhdGhfY3JlYXRlX2RpcmVjdG9yeQAAFndhc2lfc25hcHNob3RfcHJldmlldzEJcGF0aF9vcGVuAAEWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQpmZF9yZWFkZGlyAAIWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQhmZF93cml0ZQADAwIBBAUDAQABBxMCBm1lbW9yeQIABl9zdGFydAAECnkBdwEBf0EDQeQAQQMQABpBA0EAQeQAQQNBAkL/////A0L/////A0EAQcAAEAEaQcAAKAIAIQAgAEGQA0HIAUIAQTgQAhpByAFBMEE4KAIAQQBHajoAAEHJAUEKOgAAQSBByAE2AgBBJEECNgIAQQFBIEEBQSgQAxoLCwoBAEHkAAsDc3Vi',
  'filestat':        'AGFzbQEAAAABJwVgCX9/f39/fn5/fwF/YAR/f39/AX9gAX8Bf2AFf39/f38Bf2AAAAKTAQQWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQlwYXRoX29wZW4AABZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxCGZkX3dyaXRlAAEWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQhmZF9jbG9zZQACFndhc2lfc25hcHNob3RfcHJldmlldzERcGF0aF9maWxlc3RhdF9nZXQAAwMCAQQFAwEAAQcTAgZtZW1vcnkCAAZfc3RhcnQABAqQAQGNAQEBf0EDQQBB5ABBCEEBQv////8DQv////8DQQBBwAAQABpBwAAoAgAhAEEgQfgANgIAQSRBDTYCACAAQSBBAUEoEAEaIAAQAhpBA0EAQeQAQQhBkAMQAxpByAFBMEGwAygCAEEKcGo6AABByQFBCjoAAEEgQcgBNgIAQSRBAjYCAEEBQSBBAUEoEAEaCwsiAgBB5AALCGRhdGEuYmluAEH4AAsNaGVsbG8sIHdvcmxkIQ==',
  'pread-pwrite':    'AGFzbQEAAAABMAZgCX9/f39/fn5/fwF/YAR/f39/AX9gAX8Bf2AFf39/fn8Bf2AFf39/fn8Bf2AAAAKtAQUWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQlwYXRoX29wZW4AABZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxCGZkX3dyaXRlAAEWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQhmZF9jbG9zZQACFndhc2lfc25hcHNob3RfcHJldmlldzEIZmRfcHJlYWQAAxZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxCWZkX3B3cml0ZQAEAwIBBQUDAQABBxMCBm1lbW9yeQIABl9zdGFydAAFCqcBAaQBAQF/QQNBAEHkAEEIQQFC/////wNC/////wNBAEHAABAAGkHAACgCACEAQSBB+AA2AgBBJEEINgIAIABBIEEBQSgQARpBIEGMATYCAEEkQQI2AgAgAEEgQQFCA0EoEAQaQSBBrAI2AgBBJEEFNgIAIABBIEEBQgFBKBADGiAAEAIaQbECQQo6AABBIEGsAjYCAEEkQQY2AgBBAUEgQQFBKBABGgsLJQMAQeQACwhkYXRhLnR4dABB+AALCGFiY2RlZmdoAEGMAQsCWFk=',
  'rename-existing': 'AGFzbQEAAAABMAZgCX9/f39/fn5/fwF/YAR/f39/AX9gBH9/f38Bf2ABfwF/YAZ/f39/f38Bf2AAAAKuAQUWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQlwYXRoX29wZW4AABZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxCGZkX3dyaXRlAAEWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQdmZF9yZWFkAAIWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQhmZF9jbG9zZQADFndhc2lfc25hcHNob3RfcHJldmlldzELcGF0aF9yZW5hbWUABAMCAQUFAwEAAQcTAgZtZW1vcnkCAAZfc3RhcnQABQqHAgGEAgEBf0EDQQBB5ABBAUEBQv////8DQv////8DQQBBwAAQABpBwAAoAgAhAEEgQfgANgIAQSRBAjYCACAAQSBBAUEoEAEaIAAQAxpBA0EAQe4AQQFBAUL/////A0L/////A0EAQcAAEAAaQcAAKAIAIQBBIEGCATYCAEEkQQI2AgAgAEEgQQFBKBABGiAAEAMaQQNB5ABBAUEDQe4AQQEQBBpBA0EAQe4AQQFBAEL/////A0L/////A0EAQcAAEAAaQcAAKAIAIQBBIEGsAjYCAEEkQQg2AgAgAEEgQQFBKBACGiAAEAMaQSBBrAI2AgBBJEEoKAIANgIAQQFBIEEBQSgQARoLCx8EAEHkAAsBYQBB7gALAWIAQfgACwJBCgBBggELAkIK',
  'cat':             'AGFzbQEAAAABMgdgAn9/AX9gAn9/AX9gCX9/f39/fn5/fwF/YAR/f39/AX9gBH9/f38Bf2ABfwF/YAAAAtMBBhZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxDmFyZ3Nfc2l6ZXNfZ2V0AAAWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQhhcmdzX2dldAABFndhc2lfc25hcHNob3RfcHJldmlldzEJcGF0aF9vcGVuAAIWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQdmZF9yZWFkAAMWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQhmZF93cml0ZQAEFndhc2lfc25hcHNob3RfcHJldmlldzEIZmRfY2xvc2UABQMCAQYFAwEAAQcTAgZtZW1vcnkCAAZfc3RhcnQABgqaAQGXAQECf0EAQQQQABpBEEHIARABGkEUKAIAIQFBA0EAIAFBCUEAQv////8DQv////8DQQBBwAAQAhpBwAAoAgAhAAJAA0BB5ABBgAg2AgBB6ABBgCA2AgAgAEHkAEEBQcgAEAMaQcgAKAIARQ0BQeQAQYAINgIAQegAQcgAKAIANgIAQQFB5ABBAUHIABAEGgwACwsgABAFGgs=',
};

export function writeFixtureCmd(name, vfsPath) {
  const b64 = FIXTURES[name];
  if (!b64) throw new Error(`unknown fixture: ${name}`);
  return `node -e "require('fs').writeFileSync('${vfsPath}', Buffer.from('${b64}','base64'))"`;
}
