import assert from 'node:assert/strict';
import { openRuntimeStdio } from '../../packages/core/src/runtime/runtime-stdio.ts';
import { SessionProcessSupervisor } from '../../packages/core/src/runtime/session-process-supervisor.ts';
import { installedRuntime, runtimeContext } from './lib/runtime-session.mjs';
const {filesystem}=installedRuntime();
const processes=new SessionProcessSupervisor();
const parent=processes.spawn('sh',['sh'],'/home/user');
const outputs=[[],[]];
const invoke=index=>openRuntimeStdio({filesystem,processes},runtimeContext(filesystem,{pid:parent.pid,stdout:{write(){throw new Error('bytes must not be decoded')},writeBytes:b=>outputs[index].push(b.slice())},stderr:{write(){}},signal:new AbortController().signal}).ctx,'python');
const first=invoke(0),second=invoke(1),raw=new Uint8Array([255,254,0,128]);
assert.notEqual(first.pid,second.pid,'every standalone invocation is a distinct process');
await processes.appendOutputBytes(first.pid,'stdout',raw);
await processes.appendOutputBytes(second.pid,'stdout',raw.subarray(1));
assert.deepEqual(outputs,[[raw],[raw.subarray(1)]],'simultaneous commands do not cross their launching fds');
first.finish(0);second.finish(0);
const child=processes.spawn('python',['python'],'/home/user',{parentPid:parent.pid});
processes.openInput(child.pid);processes.writeInputBytes(child.pid,raw);processes.endInput(child.pid);
const entry=openRuntimeStdio({filesystem,processes},runtimeContext(filesystem,{pid:child.pid,__nimbusBinSpawn:{callerPid:child.pid,liveInput:true},signal:new AbortController().signal}).ctx,'python');
assert.equal(entry.pid,child.pid,'a broker-owned runtime keeps its existing pid');
assert.deepEqual((await processes.readInput(entry.pid,0)).data,raw);
entry.finish(0);processes.exit(child.pid,0);
console.log('runtime-stdio: byte fds, isolated concurrent invocations and broker-owned shared fd0');
